### ISSUE TITLE
Captain America Super Soldier NDS textures can't be converted

### ISSUE THREAD

**Issue by Tosyk** [scurest/apicula#11]
hello,
I've tried Captain America Super Soldier NDS textures without success. Though apicula recognized nsbtx as textures it can't convert them.
is it possible you can take a look at them?
[captain_america_super_soldier_nds.zip](https://github.com/scurest/apicula/files/2386895/captain_america_super_soldier_nds.zip)

**Comment by scurest** [comment]
Sure. I'm able to dump them with

    apicula convert --more-textures hatch1.nsbtx INC.nsbtx

![final](https://user-images.githubusercontent.com/11024420/45601163-2a5dec00-b9ce-11e8-9417-a3b2fb2d3cfc.png)

See #3 and #5 for more info about the `--more-textures` flag.

I should probably get around to adding some kind of notice that appears when there are unused textures that tells you what to do if you want them...

**Comment by Tosyk** [comment]
thanks, good to know though I still can't extract anything
all I'm getting is:
`Got 0 models, 1 texture, 1 palette, 0 animations.
Wrote 0 DAEs, 0 PNGs.`

**Comment by scurest** [comment]
The two files you uploaded each have one texture and no palettes. I get

```
Got 0 models, 2 textures, 0 palettes, 0 animations.
[INFO] guessed 2 new images (for --more-textures)
Wrote 0 DAEs, 2 PNGs.
```

This is using 21859fe.

You can see info about the files you provided with the `info` subcommand.

**Comment by Tosyk** [comment]
I tried it with the texture I provided earlier (hatch1.nsbtx INC.nsbtx) and it's worked.
however it doesn't work with this one: 

[Arm.zip](https://github.com/scurest/apicula/files/2555492/Arm.zip)

**Comment by scurest** [comment]
You're right! I was missing a `\`! It should be fixed now. Can you check?

**Comment by Tosyk** [comment]
> You're right! I was missing a `\`! It should be fixed now. Can you check?

sure, I'll take a look when I get back home and will response here

**Comment by scurest** [comment]
@Tosyk Did you ever get a chance to see if this is fixed?

**Comment by Tosyk** [comment]
@scurest I might check right now
