### ISSUE TITLE
All model UVs are flipped

### ISSUE THREAD

**Issue by Tosyk** [scurest/apicula#13]
I’ve noticed that all the game model I’ve tried so far had flipped uv.
It’s cod black ops/mw3, captain america, kingdom hearts.
Having “FlipUV” as an option or hard coded flip of uv wouldn’t be much of a trouble?

**Comment by scurest** [comment]
What do you mean by flipped UVs? The U coordinate is always flipped from its DS value because on the DS the origin is at the upper-left of the texture while in COLLADA it is at the bottom-left.

**Comment by Tosyk** [comment]
Yeah, I've checked 'openCOLLADA' and 'COLLADA' import plugins for 3ds max and they both loads correct uv. You were right.
p.s.: the noesis COLLADA module do not load uv flipped as it should, that's why I thought uv is wrong.
