### ISSUE TITLE
Exporting all textures

### ISSUE THREAD

**Issue by MannedTooth** [scurest/apicula#14]
Hey there, so I have this model which has 4 different textures (same model shared between 4 different-colored characters). I seem to be only able to extract the first textures. Though, when fiddling around in the texture/palette viewer, I can see all of them. I thought I would take a screen capture of it and use it as if, but there's this black outline which is covering a pixel all around the image, resulting in a 62x62 texture instead of a 64x64. 
![image](https://user-images.githubusercontent.com/15331466/54481731-fe051a00-480e-11e9-8054-dfa94c24b598.png)

Is there anyway to export all different textures from a .nbstx? And optionally, would it be possible for the texture viewer not to cover part of the texture? Thanks.

**Comment by scurest** [comment]
@MannedTooth Is this filed on the right repo? There isn't a texture viewer here, haha.

**Comment by MannedTooth** [comment]
Oh my god, you're right. Sorry about that, this is an issue for OpenTool.
