### ISSUE TITLE
[Suggestion] Viewer movement speed

### ISSUE THREAD

**Issue by mariomadproductions** [scurest/apicula#2]
Instead of using shift to speed it up by a fixed amount, could you make it so you can use the +/- or number keys (optionally in combination with shift) to adjust the speed to how you want it?

Thanks

**Comment by scurest** [comment]
You mean +/- instead of Shift/Ctrl? Sorry, I don't understand what you mean about the number keys.

(Oops, also just noticed that the controls say R.Ctrl slows down. It's actually L.Ctrl.)

**Comment by mariomadproductions** [comment]
I meant adding more than two speed options. E.g. by increasing/decreasing the speed by a number with +/- or having the speeds mapped to the number keys.

**Comment by scurest** [comment]
I think you're on an old version; try the latest. Starting from 14cc88e, there are nine speeds. You should be able to increase the speed in steps by tapping L.Shift. I added that because the old way was too slow, just like you said.
