### ISSUE TITLE
Call Of Duty Modern Warfare roomset NSBMDs not working

### ISSUE THREAD

**Issue by CrashOveride95** [scurest/apicula#20]
I am trying to convert roomset nsbmds but apicula will not read them. I checked the fileheaders and for some reason they are "BDL0" and not BMD0.

I suspect compression, but i can't tell.

I have included a sample.
[Intro.zip](https://github.com/scurest/apicula/files/3330960/Intro.zip)

**Comment by scurest** [comment]
Hmmm. They don't look like NSBMDs to me. I don't know anything about a BDL0 format.

The best I can tell you is that if you think it's compressed, it would presumably be decompressed at run-time, so you could play the game in an emulator until the model is on-screen, dump the memory, and try to extract any NSBMDs from the memory dump (see [EXTRACT](https://github.com/scurest/apicula/wiki/EXTRACT)). That's kind of the strategy of last resort before you have to actually understand whatever format those files are using.

**Comment by CrashOveride95** [comment]
that didn't work, they might be a different format entirely.
