### ISSUE TITLE
Refuses to start

### ISSUE THREAD

**Issue by ItzDannio25** [scurest/apicula#27]
When I click in the program a cmd window opens for 1 second and then it closes, I have rust 1.34 installed.

**Comment by scurest** [comment]
Run it from the command line.

**Comment by DevChaotic** [comment]
Even ran from the command line the issue still continues. 
[CMDFail-Clip.zip](https://github.com/scurest/apicula/files/5046587/CMDFail-Clip.zip)

**Comment by scurest** [comment]
Type `apicula.exe` at the prompt.

**Comment by DevChaotic** [comment]
Thank you, works perfectly now.
