### ISSUE TITLE
apicula crashes immediately after launching

### ISSUE THREAD

**Issue by Luke-L** [scurest/apicula#32]
have i maybe installed it wrong or something?

**Comment by scurest** [comment]
Are you running it from the command line?

**Comment by Luke-L** [comment]
> Are you running it from the command line?
i have that figured out now and it seems to be running, but refuses to extract/unpack the files i give it. see below.
[mdl.zip](https://github.com/scurest/apicula/files/5818699/mdl.zip)

![apiculaissue](https://user-images.githubusercontent.com/19858052/104686487-ec1e8780-56c2-11eb-920f-8c01d248073a.JPG)

**Comment by scurest** [comment]
That's normal since none of those are recognizably Nitro files. Looking at them in a hex editor, there's nothing recognizable to me at all. You can't assume it's the right kind of file just based on the file extension.

See if you can get anything out of the ROM with `apicula extract your_rom.nds -o output_dir`. If you can't then there's nothing I can tell you.

**Comment by Luke-L** [comment]
Thanks, that seems to work for extracting files (although i was just using desmume before) but now the directory system has not been retained and is completely fucked lol. is it supposed to just chuck all of the files into one big folder?
![apiculaissue2](https://user-images.githubusercontent.com/19858052/104688959-533e3b00-56c7-11eb-8eb9-ee2d0af2f21f.JPG)

**Comment by scurest** [comment]
Yes. There are some ideas for extracting files on the [EXTRACT](https://github.com/scurest/apicula/wiki/EXTRACT) page on the wiki. You may be interested in [Recursively extract from a filesystem dump](https://github.com/scurest/apicula/wiki/EXTRACT#recursively-extract-from-a-filesystem-dump).

**Comment by Luke-L** [comment]
thanks for your help :)

**Comment by scurest** [comment]
Np
