### ISSUE TITLE
NSBTX textures don't get converted to PNGs

### ISSUE THREAD

**Issue by vSxnc** [scurest/apicula#34]
When I try to convert the .nsbtx format to a .png using the command:
"apicula convert filename.nsbtx --more-textures --output mapname"
it doesn't output the textures as png, in the commandline it does show that it found the textures and the amount of
palettes but it doesn't output them as png.

**Comment by scurest** [comment]
They're probably named weird. Give me the .nsbtx.

**Comment by scurest** [comment]
No response
