### ISSUE TITLE
Maintain FileSystem structure?

### ISSUE THREAD

**Issue by keanine** [scurest/apicula#35]
It would be ideal if extracting and converting each model could maintain the file structure of the given game.

For example, Mario Kart DS contains the structure:
mkds/root/data/Course/airship_course.carc/airship_course.carc
So it would be great if the .nsbxx's could be found in:
extract-folder/root/data/Course/airship_course.carc/airship_course/airship_course.nsbxx
This would make it far easier to navigate and know which files are required for each nsbmd

The same could be done for converting too, making the models self contained!

**Comment by scurest** [comment]
There's a [Python script](https://gist.github.com/scurest/635f2ab5fe0651bf0cc10113e50cc6e2) on the wiki that uses ndstool to extract the filesystem structure and apicula to extract the Nitro files.
