### ISSUE TITLE
NSBTX file doesn't get converted to PNG

### ISSUE THREAD

**Issue by Ghostrider231** [scurest/apicula#36]
Hello,

When I try convert a .nsbtx file to .png file using this command (EX):
**`apicula convert ww.nsbtx --more-textures -o test`**
or
**`apicula convert ww.nsbtx -o test`**

The program acknowledges the textures in the nsbtx file, but it won't actually extract anything to png.
It doesn't really matter what I name the file. The same result happens.

Using **`apicula convert *.nsbtx -o test`** also outputs the same result.

Case if you need the file: https://www.mediafire.com/file/znpnv4vocdmghhj/ww.nsbtx/file
(It's original name is h_kage.110.nsbtx)

**Comment by scurest** [comment]
There was a type that made `--more-textures` not work. Should be fixed.
