### ISSUE TITLE
Crashes when minimizing

### ISSUE THREAD

**Issue by As1th** [scurest/apicula#38]
Something marginally similar has been reported before, but apicula completely bricks Windows if I minimize the viewer. It seems exponential: as soon as I minimize, all of windows drastically slows down. If I can click on the taskbar to bring apicula up again quickly enough, everything is instantly fixed. However, if I leave it minimized for more than 3 seconds, everything is halted beyond salvation. Nothing on the screen responds whatsoever and a forced restart is the only option. I've tried this on two seperate machines, one with Windows 8 and one with Windows 10, both with the exact same issue. It surprises me that this hasn't been reported before considering it effects both my machines.
It might have something to do with my tendency to open many models at once.

**Comment by scurest** [comment]
This may have been because vsync was not enabled, so it tried to run at a zillion frames per second. Vsync is enabled now.
