### ISSUE TITLE
Only extracting Textures? 

### ISSUE THREAD

**Issue by SameplayerDE** [scurest/apicula#41]
Is there a way, a plan to add it in the future, to only extract textures (sprites, textures, ui)

**Comment by scurest** [comment]
I don't see the point. I don't plan to add any new features though.

**Comment by SameplayerDE** [comment]
Because UI textures are not used with any models and I cant convert the nsbtx files without it being used in any nsbmd file.
:(

**Comment by scurest** [comment]
Oh, you mean convert. You can pass `--more-textures` to get unused textures, but it still won't convert textures where it can't guess what palette it should use. There's a bunch of issues about this already.

You can also use [this](https://scurest.github.io/BTXViewer/viewer.html) for viewing textures. It lets you swap the palettes too.

**Comment by SameplayerDE** [comment]
.\apicula.exe convert <nsbmd_file> --output  <output_dir> --more-textures
like this?

**Comment by SameplayerDE** [comment]
or do I have to do it like this
.\apicula.exe convert .\blabla\.* --output <output_dir> --more-textures
