### ISSUE TITLE
SM64DS seems to yield no results?

### ISSUE THREAD

**Issue by RedBrumbler** [scurest/apicula#45]
As described, SM64DS yields no results when it comes to extracting models from the rom, is this a known issue with the sm64ds game or is it just my rom?

![image](https://user-images.githubusercontent.com/51795403/155405263-d071d125-4f40-4e8d-98be-b7b028a62da3.png)

**Comment by scurest** [comment]
IIRC SM64 uses some kind of proto-BMD format different from the regular BMD format so it won't work.

**Comment by RedBrumbler** [comment]
dang that sucks, this program seemed to be great to get correct animation data out of the game... SM64DSe is exporting the animation data in a weird way causing it to not be correct and I just can't seem to figure out what's going wrong with it
