### ISSUE TITLE
Unable to just extract textures from NSBTX

### ISSUE THREAD

**Issue by NickGurMatic69** [scurest/apicula#5]
Pokemon games usually have a separate narcs for map textures and models, however it's tedious to find them without extracting all the textures at once, which Apicula can't extract textures from just NSBTX files.

**Comment by scurest** [comment]
Take a look at #3.

The problem with dumping images from an NSBTX file is that to get an image you need (1) a texture, and (2) a palette, telling you what the colors in the texture are. So if you get a big pile of textures and palettes (which is what an NSBTX is) you don't know which texture-palette pairs match up to form meaningful images. To get images for a model file, we can just generate them "on-demand" from what the model files uses, but without one, I don't know what to do.

Try using the `--more-textures` option I mentioned in #3 and see if that gets you anything usable.

**Comment by NickGurMatic69** [comment]
Thanks, This worked on the nsbtx.
