### ISSUE TITLE
macOS: command not found

### ISSUE THREAD

**Issue by reppoy** [scurest/apicula#50]
Hi, I've followed the build instructions and I'm getting this error:
`zsh: command not found: apicula`

If it helps, I get this warning when I build it:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/1904372/201440224-93888e1e-146e-41fe-8bd7-de9a169e77b3.png">

Things seem to work if I run it like this with the file in the release folder:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/1904372/201441040-9fecd4ce-bcae-4c6d-86cd-d23c98381002.png">

Let me know if you need more details on my end, I might just be missing a step. It's not a huge deal if I have to use it like this.

**Comment by scurest** [comment]
Hi. Yes, it's the same as any command line program. You either give the path to the executable or you can put the binary in your PATH.
