### ISSUE TITLE
New version incredibly slow

### ISSUE THREAD

**Issue by As1th** [scurest/apicula#63]
Apicula is now unusably slow especially when using mouse controls. Wasn't a problem until last week's commits
(Windows)

**Comment by scurest** [comment]
Thanks. Can you try again?

**Comment by As1th** [comment]
The slowness has been fixed. However this update has also caused the viewer to render models completely incorrectly - completely black even when textures are found and apparently being read

**Comment by scurest** [comment]
Textures work for me. Open an issue with the necessary files to repro if you want me to look.
