### ISSUE TITLE
Textures no longer display on windows viewer

### ISSUE THREAD

**Issue by As1th** [scurest/apicula#64]
Latest commits have broken texture display on windows. Using these 3 files for repro:
[P2A3b.zip](https://github.com/user-attachments/files/16469032/P2A3b.zip)

More info:
1) Older version of the viewer displays these textures correctly
![image](https://github.com/user-attachments/assets/c60b55d2-dbaa-4312-888d-03eab6063881)

2) New viewer doesn't display textures
![image](https://github.com/user-attachments/assets/e9d710a4-bbf2-4340-95e9-b78b1642adb5)

3) Textures are apparently being read
![image](https://github.com/user-attachments/assets/56838516-c7de-4751-963b-73f623041b7f)

4) Textures are present correctly after export. Purely a viewer issue
![image](https://github.com/user-attachments/assets/ddb7ae3a-d103-4db2-b149-37a9bb50b2ab)

**Comment by scurest** [comment]
Thanks for the files. I can repro on Windows only (works on Linux).

Unfortunately it appears the same problem occurs even when compiling the old source code, so I can only assume it is some kind of interaction with the current version of the compiler. I will try updating all the dependencies and see if that fixes it. I'll try to get to it later today.

**Comment by scurest** [comment]
That was a minor nightmare, but it now works on Windows in my tests. Can you test again?

**Comment by As1th** [comment]
Yep, everything's fixed 👍 
Thanks for the effort on this tool

**Comment by scurest** [comment]
Thanks. Sorry it took so long to fix vsync.
