### ISSUE TITLE
Extract a single animation from a .nsbca file

### ISSUE THREAD

**Issue by MannedTooth** [scurest/apicula#9]
Hey there!

Thank you for your software, it is so nice and I'm having a blast with it so far. I was wondering if there was any way of extracting only a certain animation out of a `.nsbca` file. Once again, my example is with Phantom Hourglass. I am able to see all animations of a model by using view, but when converting to `.dae` it only appears to give me the first one. I want the last one. Is there any way of doing that?

**Comment by scurest** [comment]
I'm glad you're having fun :)

If you're importing into Blender, it has an issue where it doesn't handle multiple animations in a COLLADA file. But you can use [Inferry's cool `.dae` splitter](https://www.vg-resource.com/thread-30547-post-634261.html#pid634261) from VG Resource to turn a `.dae` with multiple animations into multiple `.dae`s with one animations each. I just tested it with Link and it seems to work fine.

If you're importing into something else multiple animations should work, but I've only tested this in Godot.

**Comment by MannedTooth** [comment]
I sure am! :)

Thank you so much for that queue! It seems like it's working like a charm.
